=== vinssoke/class-project/videogames.dtd
<!ELEMENT VideogameChain (Company+)>
<!ATTLIST VideogameChain name CDATA #REQUIRED>

<!ELEMENT Company (Name, Founded, Country, Videogames)>
<!ATTLIST Company id ID #REQUIRED>

<!ELEMENT Name (#PCDATA)>
<!ELEMENT Founded (#PCDATA)>
<!ELEMENT Country (#PCDATA)>

<!ELEMENT Videogames (Videogame+)>
<!ELEMENT Videogame (Title, Genre, ReleaseYear)>

<!ELEMENT Title (#PCDATA)>
<!ELEMENT Genre (#PCDATA)>
<!ELEMENT ReleaseYear (#PCDATA)>

=== vinssoke/class-project/videogames.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE VideogameChain SYSTEM "videogames.dtd">

<VideogameChain name="Gaming World Inc.">
    <Company id="C001">
        <Name>Nintendo</Name>
        <Founded>1889</Founded>
        <Country>Japan</Country>
        <Videogames>
            <Videogame>
                <Title>The Legend of Zelda: Breath of the Wild</Title>
                <Genre>Adventure</Genre>
                <ReleaseYear>2017</ReleaseYear>
            </Videogame>
            <Videogame>
                <Title>Super Mario Odyssey</Title>
                <Genre>Platform</Genre>
                <ReleaseYear>2017</ReleaseYear>
            </Videogame>
        </Videogames>
    </Company>

    <Company id="C002">
        <Name>Sony Interactive Entertainment</Name>
        <Founded>1993</Founded>
        <Country>Japan</Country>
        <Videogames>
            <Videogame>
                <Title>The Last of Us Part II</Title>
                <Genre>Action/Adventure</Genre>
                <ReleaseYear>2020</ReleaseYear>
            </Videogame>
            <Videogame>
                <Title>God of War</Title>
                <Genre>Action</Genre>
                <ReleaseYear>2018</ReleaseYear>
            </Videogame>
        </Videogames>
    </Company>

    <Company id="C003">
        <Name>Microsoft Studios</Name>
        <Founded>2002</Founded>
        <Country>United States</Country>
        <Videogames>
            <Videogame>
                <Title>Halo Infinite</Title>
                <Genre>Shooter</Genre>
                <ReleaseYear>2021</ReleaseYear>
            </Videogame>
            <Videogame>
                <Title>Forza Horizon 5</Title>
                <Genre>Racing</Genre>
                <ReleaseYear>2021</ReleaseYear>
            </Videogame>
        </Videogames>
    </Company>
</VideogameChain>
